### PR TITLE
ENH Icon alignment

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Description

Screenshot 2024-02-14 at 9 02 10 AM

## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/194

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
New alignment looks good in chrome but doesn't work for firefox.

**Comment by GuySartorelli** [comment]
That said, don't spend too long on this - it's a super low priority. If it starts looking like it'll take a while just dump it in the icebox.

**Comment by sabina-talipova** [comment]
Now should looks better.
### Chrome:

Screenshot 2024-02-14 at 12 22 15 PM

### Firefox:

Screenshot 2024-02-14 at 12 19 35 PM


Screenshot 2024-02-14 at 12 25 52 PM

**Review by GuySartorelli — APPROVED** [review]
LGTM, will merge on green

**Pull request merged**
