### PR TITLE
Enable updateDescription to override the Description

### PR DESCRIPTION
**Pull request by ishannz**
## Description
We are upgrading from version 3 to 4.0.7, and we have a custom field called "Description" under the Link dataobject. 
After the upgrade to version 4.0.7, the Description field does not return the correct value. 

This fix will allow users to override the Description value if needed.

Please make sure to support CMS version 5.2 by creating the right tag.

## Issues

- #

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

### CODE REVIEW

**Review by michalkleiner — COMMENTED** [review]
This makes sense from my perspective ✅

**Comment by GuySartorelli** [comment]
Please create an issue and link to it, and include any manual testing steps, and tick all the boxes that apply in the PR description. If you're unsure about any of the boxes after reading the linked documentation, please ask.

> we have a custom field called "Description" under the Link dataobject

What is the purpose of that field? And what is the intended use case for updating the description which gets returned by `getDescription()`?

**Comment by GuySartorelli** [comment]
> Please make sure to support CMS version 5.2 by creating the right tag.

New extension hooks are typically added in minor releases, not in patch releases.

**Comment by ishannz** [comment]
> What is the purpose of that field? And what is the intended use case for updating the description which gets returned by getDescription()?

It's a custom field in the project used for link description, which was an existing field before the upgrade.

**Comment by GuySartorelli** [comment]
Right, so what does the extension hook do for you? You shouldn't use it to return your pre-existing field value because `getDescription` is used for a specific purpose in the link field.

**Comment by GuySartorelli** [comment]
It sounds like for the current major release line you will probably need to rename your field, and perhaps open an issue to change the name of `getDescription` to something less generic in a future major release.

**Comment by ishannz** [comment]
I changed the name to LinkDescription and migrated the data.

**Comment by GuySartorelli** [comment]
Sounds like you don't need this change anymore, so I'm going to close it.
Feel free to open an issue about changing `getDescription` to something more generic in CMS 6.

**Pull request closed without merging**
